/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroAguardandoLiberacaoRouteImport } from './routes/cadastro.aguardando-liberacao'
import { Route as AuthenticatedOsRouteImport } from './routes/_authenticated/os'
import { Route as AuthenticatedOperadoresRouteImport } from './routes/_authenticated/operadores'
import { Route as AuthenticatedMaquinasRouteImport } from './routes/_authenticated/maquinas'
import { Route as AuthenticatedEmpresasRouteImport } from './routes/_authenticated/empresas'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedConfiguracoesRouteImport } from './routes/_authenticated/configuracoes'
import { Route as AuthenticatedChecklistsRouteImport } from './routes/_authenticated/checklists'
import { Route as AuthenticatedAlertasRouteImport } from './routes/_authenticated/alertas'
import { Route as AuthenticatedEmpresasNovaRouteImport } from './routes/_authenticated/empresas.nova'
import { Route as AuthenticatedEmpresasIdEditarRouteImport } from './routes/_authenticated/empresas.$id.editar'
import { Route as AuthenticatedEmpresasIdConfiguracoesRouteImport } from './routes/_authenticated/empresas.$id.configuracoes'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroAguardandoLiberacaoRoute =
  CadastroAguardandoLiberacaoRouteImport.update({
    id: '/aguardando-liberacao',
    path: '/aguardando-liberacao',
    getParentRoute: () => CadastroRoute,
  } as any)
const AuthenticatedOsRoute = AuthenticatedOsRouteImport.update({
  id: '/os',
  path: '/os',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedOperadoresRoute = AuthenticatedOperadoresRouteImport.update({
  id: '/operadores',
  path: '/operadores',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMaquinasRoute = AuthenticatedMaquinasRouteImport.update({
  id: '/maquinas',
  path: '/maquinas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasRoute = AuthenticatedEmpresasRouteImport.update({
  id: '/empresas',
  path: '/empresas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedConfiguracoesRoute =
  AuthenticatedConfiguracoesRouteImport.update({
    id: '/configuracoes',
    path: '/configuracoes',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedChecklistsRoute = AuthenticatedChecklistsRouteImport.update({
  id: '/checklists',
  path: '/checklists',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAlertasRoute = AuthenticatedAlertasRouteImport.update({
  id: '/alertas',
  path: '/alertas',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedEmpresasNovaRoute =
  AuthenticatedEmpresasNovaRouteImport.update({
    id: '/nova',
    path: '/nova',
    getParentRoute: () => AuthenticatedEmpresasRoute,
  } as any)
const AuthenticatedEmpresasIdEditarRoute =
  AuthenticatedEmpresasIdEditarRouteImport.update({
    id: '/$id/editar',
    path: '/$id/editar',
    getParentRoute: () => AuthenticatedEmpresasRoute,
  } as any)
const AuthenticatedEmpresasIdConfiguracoesRoute =
  AuthenticatedEmpresasIdConfiguracoesRouteImport.update({
    id: '/$id/configuracoes',
    path: '/$id/configuracoes',
    getParentRoute: () => AuthenticatedEmpresasRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/login': typeof LoginRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/checklists': typeof AuthenticatedChecklistsRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/maquinas': typeof AuthenticatedMaquinasRoute
  '/operadores': typeof AuthenticatedOperadoresRoute
  '/os': typeof AuthenticatedOsRoute
  '/cadastro/aguardando-liberacao': typeof CadastroAguardandoLiberacaoRoute
  '/empresas/nova': typeof AuthenticatedEmpresasNovaRoute
  '/empresas/$id/configuracoes': typeof AuthenticatedEmpresasIdConfiguracoesRoute
  '/empresas/$id/editar': typeof AuthenticatedEmpresasIdEditarRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRouteWithChildren
  '/login': typeof LoginRoute
  '/alertas': typeof AuthenticatedAlertasRoute
  '/checklists': typeof AuthenticatedChecklistsRoute
  '/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/maquinas': typeof AuthenticatedMaquinasRoute
  '/operadores': typeof AuthenticatedOperadoresRoute
  '/os': typeof AuthenticatedOsRoute
  '/cadastro/aguardando-liberacao': typeof CadastroAguardandoLiberacaoRoute
  '/empresas/nova': typeof AuthenticatedEmpresasNovaRoute
  '/empresas/$id/configuracoes': typeof AuthenticatedEmpresasIdConfiguracoesRoute
  '/empresas/$id/editar': typeof AuthenticatedEmpresasIdEditarRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/cadastro': typeof CadastroRouteWithChildren
  '/login': typeof LoginRoute
  '/_authenticated/alertas': typeof AuthenticatedAlertasRoute
  '/_authenticated/checklists': typeof AuthenticatedChecklistsRoute
  '/_authenticated/configuracoes': typeof AuthenticatedConfiguracoesRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/empresas': typeof AuthenticatedEmpresasRouteWithChildren
  '/_authenticated/maquinas': typeof AuthenticatedMaquinasRoute
  '/_authenticated/operadores': typeof AuthenticatedOperadoresRoute
  '/_authenticated/os': typeof AuthenticatedOsRoute
  '/cadastro/aguardando-liberacao': typeof CadastroAguardandoLiberacaoRoute
  '/_authenticated/empresas/nova': typeof AuthenticatedEmpresasNovaRoute
  '/_authenticated/empresas/$id/configuracoes': typeof AuthenticatedEmpresasIdConfiguracoesRoute
  '/_authenticated/empresas/$id/editar': typeof AuthenticatedEmpresasIdEditarRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/alertas'
    | '/checklists'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/maquinas'
    | '/operadores'
    | '/os'
    | '/cadastro/aguardando-liberacao'
    | '/empresas/nova'
    | '/empresas/$id/configuracoes'
    | '/empresas/$id/editar'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/login'
    | '/alertas'
    | '/checklists'
    | '/configuracoes'
    | '/dashboard'
    | '/empresas'
    | '/maquinas'
    | '/operadores'
    | '/os'
    | '/cadastro/aguardando-liberacao'
    | '/empresas/nova'
    | '/empresas/$id/configuracoes'
    | '/empresas/$id/editar'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/_authenticated/alertas'
    | '/_authenticated/checklists'
    | '/_authenticated/configuracoes'
    | '/_authenticated/dashboard'
    | '/_authenticated/empresas'
    | '/_authenticated/maquinas'
    | '/_authenticated/operadores'
    | '/_authenticated/os'
    | '/cadastro/aguardando-liberacao'
    | '/_authenticated/empresas/nova'
    | '/_authenticated/empresas/$id/configuracoes'
    | '/_authenticated/empresas/$id/editar'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  CadastroRoute: typeof CadastroRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro/aguardando-liberacao': {
      id: '/cadastro/aguardando-liberacao'
      path: '/aguardando-liberacao'
      fullPath: '/cadastro/aguardando-liberacao'
      preLoaderRoute: typeof CadastroAguardandoLiberacaoRouteImport
      parentRoute: typeof CadastroRoute
    }
    '/_authenticated/os': {
      id: '/_authenticated/os'
      path: '/os'
      fullPath: '/os'
      preLoaderRoute: typeof AuthenticatedOsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/operadores': {
      id: '/_authenticated/operadores'
      path: '/operadores'
      fullPath: '/operadores'
      preLoaderRoute: typeof AuthenticatedOperadoresRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/maquinas': {
      id: '/_authenticated/maquinas'
      path: '/maquinas'
      fullPath: '/maquinas'
      preLoaderRoute: typeof AuthenticatedMaquinasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas': {
      id: '/_authenticated/empresas'
      path: '/empresas'
      fullPath: '/empresas'
      preLoaderRoute: typeof AuthenticatedEmpresasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/configuracoes': {
      id: '/_authenticated/configuracoes'
      path: '/configuracoes'
      fullPath: '/configuracoes'
      preLoaderRoute: typeof AuthenticatedConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/checklists': {
      id: '/_authenticated/checklists'
      path: '/checklists'
      fullPath: '/checklists'
      preLoaderRoute: typeof AuthenticatedChecklistsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/alertas': {
      id: '/_authenticated/alertas'
      path: '/alertas'
      fullPath: '/alertas'
      preLoaderRoute: typeof AuthenticatedAlertasRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/empresas/nova': {
      id: '/_authenticated/empresas/nova'
      path: '/nova'
      fullPath: '/empresas/nova'
      preLoaderRoute: typeof AuthenticatedEmpresasNovaRouteImport
      parentRoute: typeof AuthenticatedEmpresasRoute
    }
    '/_authenticated/empresas/$id/editar': {
      id: '/_authenticated/empresas/$id/editar'
      path: '/$id/editar'
      fullPath: '/empresas/$id/editar'
      preLoaderRoute: typeof AuthenticatedEmpresasIdEditarRouteImport
      parentRoute: typeof AuthenticatedEmpresasRoute
    }
    '/_authenticated/empresas/$id/configuracoes': {
      id: '/_authenticated/empresas/$id/configuracoes'
      path: '/$id/configuracoes'
      fullPath: '/empresas/$id/configuracoes'
      preLoaderRoute: typeof AuthenticatedEmpresasIdConfiguracoesRouteImport
      parentRoute: typeof AuthenticatedEmpresasRoute
    }
  }
}

interface AuthenticatedEmpresasRouteChildren {
  AuthenticatedEmpresasNovaRoute: typeof AuthenticatedEmpresasNovaRoute
  AuthenticatedEmpresasIdConfiguracoesRoute: typeof AuthenticatedEmpresasIdConfiguracoesRoute
  AuthenticatedEmpresasIdEditarRoute: typeof AuthenticatedEmpresasIdEditarRoute
}

const AuthenticatedEmpresasRouteChildren: AuthenticatedEmpresasRouteChildren = {
  AuthenticatedEmpresasNovaRoute: AuthenticatedEmpresasNovaRoute,
  AuthenticatedEmpresasIdConfiguracoesRoute:
    AuthenticatedEmpresasIdConfiguracoesRoute,
  AuthenticatedEmpresasIdEditarRoute: AuthenticatedEmpresasIdEditarRoute,
}

const AuthenticatedEmpresasRouteWithChildren =
  AuthenticatedEmpresasRoute._addFileChildren(
    AuthenticatedEmpresasRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAlertasRoute: typeof AuthenticatedAlertasRoute
  AuthenticatedChecklistsRoute: typeof AuthenticatedChecklistsRoute
  AuthenticatedConfiguracoesRoute: typeof AuthenticatedConfiguracoesRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedEmpresasRoute: typeof AuthenticatedEmpresasRouteWithChildren
  AuthenticatedMaquinasRoute: typeof AuthenticatedMaquinasRoute
  AuthenticatedOperadoresRoute: typeof AuthenticatedOperadoresRoute
  AuthenticatedOsRoute: typeof AuthenticatedOsRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAlertasRoute: AuthenticatedAlertasRoute,
  AuthenticatedChecklistsRoute: AuthenticatedChecklistsRoute,
  AuthenticatedConfiguracoesRoute: AuthenticatedConfiguracoesRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedEmpresasRoute: AuthenticatedEmpresasRouteWithChildren,
  AuthenticatedMaquinasRoute: AuthenticatedMaquinasRoute,
  AuthenticatedOperadoresRoute: AuthenticatedOperadoresRoute,
  AuthenticatedOsRoute: AuthenticatedOsRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

interface CadastroRouteChildren {
  CadastroAguardandoLiberacaoRoute: typeof CadastroAguardandoLiberacaoRoute
}

const CadastroRouteChildren: CadastroRouteChildren = {
  CadastroAguardandoLiberacaoRoute: CadastroAguardandoLiberacaoRoute,
}

const CadastroRouteWithChildren = CadastroRoute._addFileChildren(
  CadastroRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  CadastroRoute: CadastroRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
